app:
  name: "MCP Agents Cloud - 开发环境"
  description: "提供管理MCP服务器和代理的平台"
  version: "0.1.0"

api:
  prefix: "/api/v1"
  docs_url: "/docs"
  redoc_url: "/redoc"

server:
  host: "0.0.0.0"
  port: 8000
  reload: true
  workers: 1
  server_url: "http://localhost:8000"

security:
  # 开发环境密钥
  secret_key: "dev-secret-key-change-in-production"
  algorithm: "HS256"
  access_token_expire_minutes: 11520  # 8 days

cors:
  origins:
    - "http://localhost"
    - "http://localhost:8080"
    - "http://localhost:3000"
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"]

database:
  # 开发环境数据库
  url: "mysql+pymysql://mcp_user:mcp_password@192.168.101.243:63307/mcp_agents_dev"
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30
  pool_recycle: 3600

openai:
  # 开发环境OpenAI配置
  api_key: ""
  model: "gpt-3.5-turbo"
  temperature: 0.7

email:
  from_email: "dev-info@example.com"
  from_name: "MCP Agents Cloud - 开发"
  reset_token_expire_hours: 48
  templates_dir: "app/email-templates"

smtp:
  # 开发环境不发送实际邮件，可配置测试SMTP服务器
  host: ""
  port: 587
  tls: true
  user: ""
  password: "" 